
import React, { useState } from 'react';
import { AnalysisResult, IssueSeverity } from '../types';
import { Download, RefreshCw, ChevronDown, ChevronUp, CheckCircle2, FileText, Tag, Loader2, Copy, FileJson, Printer, Check } from 'lucide-react';
import { 
    ResponsiveContainer, 
    PieChart, 
    Pie, 
    Cell, 
    BarChart, 
    Bar, 
    XAxis, 
    YAxis, 
    CartesianGrid, 
    Tooltip
} from 'recharts';

interface AnalysisResultProps {
  result: AnalysisResult;
  onReanalyze: () => void;
}

const AnalysisResultView: React.FC<AnalysisResultProps> = ({ result, onReanalyze }) => {
    const [openIssueIndex, setOpenIssueIndex] = useState<number | null>(0);
    const [activeTab, setActiveTab] = useState<'detailed' | 'summary' | 'keywords'>('detailed');
    const [isExporting, setIsExporting] = useState(false);
    const [copied, setCopied] = useState(false);

    const handlePrint = () => {
        // Temporarily set document title so the saved PDF has a nice filename
        const originalTitle = document.title;
        const cleanFileName = result.fileName.replace(/\.[^/.]+$/, "").replace(/[^a-z0-9]/gi, '_');
        document.title = `Rescan_Report_${cleanFileName}`;
        
        window.print();
        
        // Restore title
        document.title = originalTitle;
    };

    const handleCopySummary = () => {
        navigator.clipboard.writeText(result.summary);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleDownloadMarkdown = () => {
        setIsExporting(true);
        
        const markdown = `
# Resume Analysis Report: ${result.fileName}
Generated by Rescan on ${new Date().toLocaleDateString()}

## Overall Scores
- **ATS Score:** ${result.atsScore}/100
- **Grammar Score:** ${result.grammarScore}/100
- **Formatting Score:** ${result.formattingScore}/100
- **Total Mistakes Found:** ${result.totalMistakes}

## Executive Summary
${result.summary}

## Key Issues & Improvements
${result.issues.map(i => `### [${i.severity.toUpperCase()}] ${i.title}\n${i.description}`).join('\n\n')}

## Action Plan
${result.improvements.map(imp => `- ${imp}`).join('\n')}

## Keywords Detected/Recommended
${result.keywords.join(', ')}
        `.trim();

        const blob = new Blob([markdown], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Rescan_Analysis_${result.fileName.replace(/\.[^/.]+$/, "")}.md`;
        document.body.appendChild(a);
        
        setTimeout(() => {
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
            setIsExporting(false);
        }, 1000);
    };

    const getSeverityStyles = (severity: IssueSeverity) => {
        switch (severity) {
            case IssueSeverity.CRITICAL: 
                return { 
                    bg: 'bg-red-950/30', 
                    text: 'text-red-400', 
                    border: 'border-red-900/50',
                    badge: 'bg-red-900/50 text-red-400'
                };
            case IssueSeverity.MODERATE: 
                return { 
                    bg: 'bg-amber-950/30', 
                    text: 'text-amber-400', 
                    border: 'border-amber-900/50',
                    badge: 'bg-amber-900/50 text-amber-400'
                };
            case IssueSeverity.SUGGESTION: 
                return { 
                    bg: 'bg-blue-950/30', 
                    text: 'text-blue-400', 
                    border: 'border-blue-900/50',
                    badge: 'bg-blue-900/50 text-blue-400'
                };
        }
    };

    // --- Chart Data ---
    const gaugeData = [
        { name: 'Score', value: result.atsScore },
        { name: 'Remaining', value: 100 - result.atsScore },
    ];
    const scoreColor = result.atsScore >= 80 ? '#10b981' : result.atsScore >= 60 ? '#f59e0b' : '#ef4444';

    const breakdownData = [
        { name: 'Keywords', score: Math.round(result.atsScore * 1.15) > 100 ? 95 : Math.round(result.atsScore * 1.15) }, 
        { name: 'Formatting', score: result.formattingScore },
        { name: 'Clarity', score: result.grammarScore },
        { name: 'Impact', score: Math.round(result.atsScore * 0.85) }, 
    ];

    const criticalIssuesCount = result.issues.filter(i => i.severity === IssueSeverity.CRITICAL).length;

    return (
        <div className="min-h-screen bg-slate-950 py-8 px-4 font-sans text-slate-200">
            <div className="container mx-auto max-w-6xl">
                
                {/* Header Section */}
                <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 gap-4 print:hidden">
                    <div>
                        <h1 className="text-3xl font-extrabold text-white tracking-tight">Analysis for {result.fileName}</h1>
                    </div>
                    <div className="flex flex-wrap gap-2">
                        <button 
                            onClick={handleDownloadMarkdown}
                            disabled={isExporting}
                            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold transition-all shadow-sm ${
                                isExporting 
                                ? 'bg-slate-800 text-slate-500 cursor-not-allowed border border-slate-700' 
                                : 'bg-slate-900 border border-slate-700 text-slate-300 hover:bg-slate-800'
                            }`}
                        >
                            {isExporting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
                            {isExporting ? 'Exporting...' : 'Markdown'}
                        </button>
                        <button 
                            onClick={handlePrint}
                            className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-semibold hover:bg-blue-700 transition-all shadow-lg shadow-blue-900/20"
                        >
                            <Printer className="w-4 h-4" /> Print PDF
                        </button>
                        <button 
                            onClick={onReanalyze}
                            className="flex items-center gap-2 px-4 py-2 bg-slate-900 border border-slate-700 text-slate-300 rounded-lg text-sm font-semibold hover:bg-slate-800 transition-colors shadow-sm"
                        >
                            <RefreshCw className="w-4 h-4" /> New Scan
                        </button>
                    </div>
                </div>

                {/* Print-only Header */}
                <div className="hidden print:block mb-8 border-b-2 border-slate-200 pb-6">
                    <div className="flex justify-between items-center">
                        <div>
                            <div className="flex items-center gap-2 mb-1">
                                <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center">
                                    <FileText className="w-5 h-5 text-white" />
                                </div>
                                <h1 className="text-4xl font-black text-slate-900">RESCAN REPORT</h1>
                            </div>
                            <p className="text-slate-500 font-medium uppercase tracking-widest text-xs">Advanced AI Resume Analysis & ATS Feedback</p>
                        </div>
                        <div className="text-right">
                            <p className="text-xs text-slate-400 font-bold uppercase tracking-tighter">Generated on</p>
                            <p className="text-sm text-slate-900 font-bold">{new Date().toLocaleDateString()}</p>
                            <p className="text-xs text-slate-400 mt-2 font-bold uppercase tracking-tighter">File Name</p>
                            <p className="text-sm text-slate-900 font-bold max-w-[200px] truncate">{result.fileName}</p>
                        </div>
                    </div>
                </div>

                {/* Key Metrics Grid */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
                    {/* Card 1: ATS Score */}
                    <div className="bg-slate-900 p-6 rounded-2xl border border-slate-800 shadow-sm flex flex-col justify-between print:border-slate-200 print:bg-white">
                        <div>
                            <h3 className="text-slate-400 font-medium text-sm print:text-slate-600">ATS Score</h3>
                            <div className="mt-2 flex items-baseline gap-2">
                                <span className="text-4xl font-extrabold text-white print:text-slate-900">{result.atsScore}</span>
                                <span className="text-sm font-medium text-slate-500">/100</span>
                            </div>
                        </div>
                        <div className="mt-4 text-xs font-semibold text-green-500 flex items-center">
                            Target: 80+ for better visibility
                        </div>
                    </div>

                    {/* Card 2: Total Mistakes */}
                    <div className="bg-slate-900 p-6 rounded-2xl border border-slate-800 shadow-sm flex flex-col justify-between print:border-slate-200 print:bg-white">
                         <div>
                            <h3 className="text-slate-400 font-medium text-sm print:text-slate-600">Total Mistakes</h3>
                            <div className="mt-2 flex items-baseline gap-2">
                                <span className="text-4xl font-extrabold text-white print:text-slate-900">{result.totalMistakes}</span>
                            </div>
                        </div>
                        <div className="mt-4 text-xs font-semibold text-slate-500 flex items-center">
                            Includes typos & grammar
                        </div>
                    </div>

                    {/* Card 3: Critical Issues */}
                    <div className="bg-slate-900 p-6 rounded-2xl border border-slate-800 shadow-sm flex flex-col justify-between print:border-slate-200 print:bg-white">
                         <div>
                            <h3 className="text-slate-400 font-medium text-sm print:text-slate-600">Critical Issues</h3>
                            <div className="mt-2 flex items-baseline gap-2">
                                <span className="text-4xl font-extrabold text-white print:text-slate-900">{criticalIssuesCount}</span>
                            </div>
                        </div>
                        <div className="mt-4 text-xs font-semibold text-red-500 flex items-center">
                            Action required immediately
                        </div>
                    </div>

                    {/* Card 4: Formatting Score */}
                    <div className="bg-slate-900 p-6 rounded-2xl border border-slate-800 shadow-sm flex flex-col justify-between print:border-slate-200 print:bg-white">
                         <div>
                            <h3 className="text-slate-400 font-medium text-sm print:text-slate-600">Formatting Score</h3>
                            <div className="mt-2 flex items-baseline gap-2">
                                <span className="text-4xl font-extrabold text-white print:text-slate-900">{result.formattingScore}</span>
                                <span className="text-sm font-medium text-slate-500">%</span>
                            </div>
                        </div>
                        <div className="mt-4 text-xs font-semibold text-blue-500 flex items-center">
                            Layout and structure
                        </div>
                    </div>
                </div>

                {/* Visual Charts Section */}
                <div className="grid md:grid-cols-2 gap-6 mb-8">
                     {/* ATS Breakdown Chart */}
                     <div className="bg-slate-900 p-6 rounded-2xl border border-slate-800 shadow-sm flex items-center gap-8 print:border-slate-200 print:bg-white">
                         <div className="h-40 w-40 shrink-0 relative">
                            <ResponsiveContainer width="100%" height="100%">
                                <PieChart>
                                    <Pie
                                        data={gaugeData}
                                        cx="50%"
                                        cy="50%"
                                        innerRadius={60}
                                        outerRadius={80}
                                        paddingAngle={0}
                                        dataKey="value"
                                        stroke="none"
                                        startAngle={90}
                                        endAngle={-270}
                                    >
                                        <Cell fill={scoreColor} cornerRadius={10} />
                                        <Cell fill="#1e293b" className="print:fill-slate-100" />
                                    </Pie>
                                </PieChart>
                            </ResponsiveContainer>
                            <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
                                <span className="text-2xl font-bold text-white print:text-slate-900">{result.atsScore}</span>
                                <span className="text-slate-500 text-xs uppercase">/ 100</span>
                            </div>
                         </div>
                         <div className="flex-1">
                             <h3 className="text-lg font-bold text-white mb-4 print:text-slate-900">ATS Score Breakdown</h3>
                             <div className="space-y-3">
                                {breakdownData.map((item, idx) => (
                                    <div key={idx} className="flex items-center justify-between">
                                        <div className="flex items-center gap-2">
                                            <div className={`w-2 h-2 rounded-full ${['bg-green-500', 'bg-amber-500', 'bg-red-500', 'bg-blue-500'][idx % 4]}`}></div>
                                            <span className="text-sm font-medium text-slate-300 print:text-slate-600">{item.name}</span>
                                        </div>
                                        <span className="text-sm font-bold text-white print:text-slate-900">{item.score}%</span>
                                    </div>
                                ))}
                             </div>
                         </div>
                     </div>

                     {/* Common Mistakes Chart */}
                     <div className="bg-slate-900 p-6 rounded-2xl border border-slate-800 shadow-sm print:border-slate-200 print:bg-white">
                         <h3 className="text-lg font-bold text-white mb-2 print:text-slate-900">Issue Distribution</h3>
                         <div className="h-40">
                             <ResponsiveContainer width="100%" height="100%">
                                 <BarChart layout="vertical" data={[
                                     { name: 'Grammar', value: 100 - result.grammarScore },
                                     { name: 'Formatting', value: 100 - result.formattingScore },
                                     { name: 'Clarity', value: Math.max(10, 100 - result.atsScore) },
                                 ]} margin={{ left: 0, right: 30 }}>
                                    <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#334155" className="print:stroke-slate-100" />
                                    <XAxis type="number" hide domain={[0, 100]} />
                                    <YAxis type="category" dataKey="name" width={80} tick={{ fontSize: 12, fill: '#94a3b8', fontWeight: 500 }} axisLine={false} tickLine={false} className="print:fill-slate-600" />
                                    <Bar dataKey="value" barSize={12} radius={[0, 4, 4, 0]}>
                                        <Cell fill="#f87171" />
                                        <Cell fill="#fbbf24" />
                                        <Cell fill="#60a5fa" />
                                    </Bar>
                                    <Tooltip 
                                        cursor={{ fill: '#1e293b' }} 
                                        contentStyle={{ backgroundColor: '#1e293b', border: '1px solid #334155', borderRadius: '8px', color: '#f8fafc' }} 
                                    />
                                 </BarChart>
                             </ResponsiveContainer>
                         </div>
                     </div>
                </div>

                <div className="mb-6">
                    <h2 className="text-xl font-bold text-white print:text-slate-900">Areas for Improvement</h2>
                </div>

                {/* Main Content Split */}
                <div className="grid lg:grid-cols-3 gap-8">
                    
                    {/* Left Column: Tabs & Content */}
                    <div className="lg:col-span-2">
                        
                        {/* Tabs (Hidden in Print) */}
                        <div className="flex border-b border-slate-800 mb-6 print:hidden">
                            <button 
                                onClick={() => setActiveTab('detailed')}
                                className={`pb-3 px-1 mr-6 text-sm font-semibold transition-colors relative ${activeTab === 'detailed' ? 'text-blue-500' : 'text-slate-500 hover:text-slate-300'}`}
                            >
                                Detailed Breakdown
                                {activeTab === 'detailed' && <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-blue-500 rounded-t-full"></div>}
                            </button>
                            <button 
                                onClick={() => setActiveTab('summary')}
                                className={`pb-3 px-1 mr-6 text-sm font-semibold transition-colors relative ${activeTab === 'summary' ? 'text-blue-500' : 'text-slate-500 hover:text-slate-300'}`}
                            >
                                Summary
                                {activeTab === 'summary' && <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-blue-500 rounded-t-full"></div>}
                            </button>
                            <button 
                                onClick={() => setActiveTab('keywords')}
                                className={`pb-3 px-1 text-sm font-semibold transition-colors relative ${activeTab === 'keywords' ? 'text-blue-500' : 'text-slate-500 hover:text-slate-300'}`}
                            >
                                Keywords
                                {activeTab === 'keywords' && <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-blue-500 rounded-t-full"></div>}
                            </button>
                        </div>

                        {/* Content Sections */}
                        <div className="space-y-8">
                            {/* Detailed Breakdown Section */}
                            <section className={`${activeTab === 'detailed' ? 'block' : 'hidden print:block'}`}>
                                <h3 className="hidden print:block text-lg font-bold text-slate-800 mb-4 uppercase tracking-wider">1. Detailed Breakdown</h3>
                                <div className="space-y-4">
                                    {result.issues.map((issue, idx) => {
                                        const styles = getSeverityStyles(issue.severity);
                                        const isOpen = openIssueIndex === idx;
                                        return (
                                            <div key={idx} className={`bg-slate-900 border rounded-xl overflow-hidden shadow-sm transition-all hover:shadow-md print:bg-white print:border-slate-200 print:shadow-none ${styles.border}`}>
                                                <button 
                                                    onClick={() => setOpenIssueIndex(isOpen ? null : idx)}
                                                    className="w-full flex items-center justify-between p-5 text-left bg-slate-900 hover:bg-slate-800/50 transition-colors print:pointer-events-none print:bg-white"
                                                >
                                                    <div className="flex items-center gap-4">
                                                        <span className={`px-2.5 py-1 rounded text-xs font-bold uppercase tracking-wider ${styles.badge}`}>
                                                            {issue.severity}
                                                        </span>
                                                        <h4 className="text-sm font-semibold text-white print:text-slate-900">{issue.title}</h4>
                                                    </div>
                                                    <div className="print:hidden">
                                                        {isOpen ? <ChevronUp className="w-5 h-5 text-slate-500" /> : <ChevronDown className="w-5 h-5 text-slate-500" />}
                                                    </div>
                                                </button>
                                                <div className={`${isOpen ? 'block' : 'hidden'} print:block px-5 pb-5 pt-0`}>
                                                    <div className="pl-2 border-l-2 border-slate-800 ml-1 print:border-slate-100">
                                                        <p className="text-sm text-slate-400 leading-relaxed pl-4 print:text-slate-600">
                                                            {issue.description}
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        );
                                    })}
                                    {result.issues.length === 0 && (
                                        <div className="text-center py-12 bg-slate-900 rounded-xl border border-slate-800 border-dashed">
                                            <CheckCircle2 className="w-10 h-10 text-green-500 mx-auto mb-3" />
                                            <h3 className="text-white font-medium">No critical issues found</h3>
                                            <p className="text-slate-400 text-sm mt-1">Your resume is in great shape!</p>
                                        </div>
                                    )}
                                </div>
                            </section>

                            {/* Summary Section */}
                            <section className={`${activeTab === 'summary' ? 'block' : 'hidden print:block'}`}>
                                <h3 className="hidden print:block text-lg font-bold text-slate-800 mb-4 uppercase tracking-wider">2. Executive Summary</h3>
                                <div className="bg-slate-900 p-8 rounded-xl border border-slate-800 shadow-sm print:bg-white print:border-slate-200 print:p-0">
                                    <div className="flex items-start gap-4">
                                        <div className="p-3 bg-blue-900/30 rounded-lg shrink-0 print:hidden">
                                            <FileText className="w-6 h-6 text-blue-500" />
                                        </div>
                                        <div className="flex-1">
                                            <div className="flex justify-between items-center mb-2 print:hidden">
                                                <h3 className="text-lg font-bold text-white">Analysis Summary</h3>
                                                <button 
                                                    onClick={handleCopySummary}
                                                    className="flex items-center gap-1.5 text-xs text-slate-500 hover:text-slate-300 transition-colors"
                                                >
                                                    {copied ? <Check className="w-3 h-3 text-green-500" /> : <Copy className="w-3 h-3" />}
                                                    {copied ? 'Copied' : 'Copy'}
                                                </button>
                                            </div>
                                            <p className="text-slate-400 leading-relaxed whitespace-pre-line print:text-slate-600 print:text-sm">
                                                {result.summary}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </section>

                            {/* Keywords Section */}
                            <section className={`${activeTab === 'keywords' ? 'block' : 'hidden print:block'}`}>
                                <h3 className="hidden print:block text-lg font-bold text-slate-800 mb-4 uppercase tracking-wider">3. Keyword Analysis</h3>
                                <div className="bg-slate-900 p-8 rounded-xl border border-slate-800 shadow-sm print:bg-white print:border-slate-200 print:p-0">
                                    <div className="flex items-start gap-4 mb-6 print:hidden">
                                        <div className="p-3 bg-purple-900/30 rounded-lg shrink-0">
                                            <Tag className="w-6 h-6 text-purple-500" />
                                        </div>
                                        <div>
                                            <h3 className="text-lg font-bold text-white">Skills & Keywords</h3>
                                            <p className="text-slate-500 text-sm mt-1">
                                                Key skills detected in your resume.
                                            </p>
                                        </div>
                                    </div>
                                    <div className="flex flex-wrap gap-2">
                                        {result.keywords && result.keywords.length > 0 ? (
                                            result.keywords.map((keyword, idx) => (
                                                <span key={idx} className="px-3 py-1.5 bg-slate-800 text-slate-300 rounded-lg text-sm font-medium border border-slate-700 print:bg-slate-50 print:border-slate-200 print:text-slate-800 print:text-xs">
                                                    {keyword}
                                                </span>
                                            ))
                                        ) : (
                                            <p className="text-slate-500 italic">No specific keywords data available.</p>
                                        )}
                                    </div>
                                </div>
                            </section>
                        </div>
                    </div>

                    {/* Right Column: Improvement Plan */}
                    <div className="lg:col-span-1 print:mt-12">
                         <div className="bg-slate-900 rounded-2xl border border-slate-800 shadow-sm p-6 sticky top-24 print:static print:bg-white print:border-slate-200 print:p-0">
                            <h2 className="text-lg font-bold text-white mb-6 print:text-slate-800 print:uppercase print:tracking-wider print:mb-4">Improvement Plan</h2>
                            
                            <div className="space-y-6 print:space-y-4">
                                {result.improvements.map((item, idx) => (
                                    <div key={idx} className="flex gap-3">
                                        <div className="shrink-0 mt-0.5">
                                            <CheckCircle2 className="w-5 h-5 text-green-500" />
                                        </div>
                                        <div>
                                            {item.includes(':') ? (
                                                <>
                                                    <span className="block text-sm font-bold text-slate-200 mb-1 print:text-slate-900">{item.split(':')[0]}:</span>
                                                    <span className="block text-sm text-slate-400 leading-relaxed print:text-slate-600 print:text-xs">{item.split(':')[1]}</span>
                                                </>
                                            ) : (
                                                <p className="text-sm text-slate-400 leading-relaxed print:text-slate-600 print:text-xs">{item}</p>
                                            )}
                                        </div>
                                    </div>
                                ))}
                            </div>
                         </div>
                    </div>

                </div>
            </div>
            <style>{`
                @media print {
                    @page { 
                        margin: 1.5cm;
                        size: A4;
                    }
                    body { 
                        background: white !important; 
                        color: #1e293b !important; 
                        -webkit-print-color-adjust: exact !important; 
                        print-color-adjust: exact !important;
                    }
                    .bg-slate-950 { background: white !important; padding: 0 !important; }
                    .container { max-width: 100% !important; padding: 0 !important; margin: 0 !important; }
                    
                    /* Force visibility of all content sections */
                    section { display: block !important; visibility: visible !important; opacity: 1 !important; margin-bottom: 2rem !important; page-break-inside: avoid; }
                    
                    h1, h2, h3, h4, span, p { color: #0f172a !important; }
                    .bg-slate-900 { background: #ffffff !important; border: 1px solid #e2e8f0 !important; box-shadow: none !important; }
                    .border-slate-800 { border-color: #e2e8f0 !important; }
                    .text-slate-400, .text-slate-500 { color: #64748b !important; }
                    
                    /* Recharts print fixes */
                    .recharts-cartesian-grid-horizontal line, .recharts-cartesian-grid-vertical line { stroke: #f1f5f9 !important; }
                    .recharts-pie-sector { stroke: white !important; }
                    
                    header, footer, .print\\:hidden { display: none !important; }
                    button { display: none !important; }
                    
                    .grid { display: block !important; }
                    .lg\\:col-span-2, .lg\\:col-span-1 { width: 100% !important; margin-bottom: 2rem; }
                    
                    .rounded-2xl, .rounded-xl { border-radius: 0.5rem !important; }
                    
                    /* Ensure score numbers are clearly visible */
                    .text-white { color: #0f172a !important; }
                    .text-4xl { font-size: 2.25rem !important; line-height: 2.5rem !important; }
                }
            `}</style>
        </div>
    );
};

export default AnalysisResultView;
